package com.question.engine.factory.impl.simple.model;

public enum QuestionBucketStatus {
	QUESTION_AVAILABLE, QUESTION_SET_TOTAL_REACHED, 
	WRONG_ANSWER_FOUND, 
	STATUS_NULL_QUESTIONS_NOT_ANSWERED,
	QUIZ_QUESTION_INITIALIZED,
	QUIZ_QUESTION_ANSWERED
}
